season:
  winter : 1
  fall  : 2
  sprint : 3
  summer : 4

hr:
  12am : 1
  1am : 2 
  2am : 3
  3am : 4
  4am : 5
  5am : 6
  6am : 7
  7am : 8
  8am : 9
  9am : 10
  10am : 11
  11am : 12
  12pm : 13
  1pm : 14
  2pm : 15
  3pm : 16
  4pm : 17
  5pm : 18
  6pm : 19
  7pm : 20
  8pm : 21
  9pm : 22
  10pm : 23
  11pm : 24

weathersit:
  Mist : 1
  Clear : 2
  Light Rain: 3
  Heavy Rain: 4

holiday:
  Yes : 1
  No :  2

workingday:
  Yes : 1
  No : 2

weekday:
  Mon : 1
  Tue : 2
  Wed : 3
  Thu : 4
  Fri : 5
  Sat : 6
  Sun : 7
